# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: BuildSetup

on:
  push:
    branches: [ "Main" ]
  pull_request:
    branches: [ "Main" ]
  workflow_dispatch: # Put here!!

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Test Print
      run: echo "${{ github.workspace }}"
    - name: List files in the repository
      run: ls ${{ github.workspace }}
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ${{ github.workspace }}/CICDPipeLineCheck
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
